export const titles = {
    withdraw: 'Withdraw ',
    deposit: 'Deposit ',
    deposit_history: 'Deposit History',
    distribution_history : 'Distribution History',
    witdraw_history: 'Withdraw History',
    open_orders: 'Open Orders',
    order_history: 'Order History',
    trade_history: 'Trade History',
    Support: 'Contact Us',
    account_verification: 'Account Verification',
    change_password: 'Change Password',
    history: 'All History',
    wallets: 'My Wallets',
    account_settings: 'Account Settings',
    login: 'Login Now',
    twofa: 'Two-Fa Verification',
    signup: 'Signup Now',
    Authorize_device: 'Authorize Device',
    forget_password: 'Forget Password',
    add_phone: 'Add Phone No',
    set_twofa: 'Set Two Fa',
    disable_twofa: 'Disable Two Fa',
    anti_phishing: 'Enable Anti Phising',
    safty_instruction: 'Safety Instructions',
    disable_phone: 'Disable Phone Verification',
    invite: 'Invite Friends',
    withdraw_confirmation: 'Withdraw Confirmation',
    reset_password: 'Reset Password',
    verify_email: 'Verify Email',
    recover_account: 'Recover Account',
    indacoin: 'Buy Crypto With Your Credit Card',
    apikey_created : 'Create New API',
    apikey : 'Manage Api Keys'
};
