export const symbolology = {
    '-11': 'Pacific/Norfolk',       // Not supporting
    '-10': 'Pacific/Honolulu',
    '-9': 'America/Juneau',         // Not Upporting
    '-8': 'America/Juneau',
    '-7': 'America/Los_Angeles',
    // '-7': 'America/Phoenix',    
    '-6': 'America/El_Salvador',
    '-5': 'America/Bogota',
    '-4': 'America/Toronto',
    '-3': 'America/Argentina/Buenos_Aires',
    //'-1': 'Europe/London',
    '0': 'Etc/UTC',
    '1': 'Europe/London',
    '2': 'Europe/Madrid',
    '3': 'Europe/Moscow',
    '330': 'Asia/Tehran',
    '4': 'Asia/Dubai',
    '5': 'Asia/Ashkhabad',
    '530': 'Asia/Kolkata',
    '6': 'Asia/Almaty',
    '7': 'Asia/Bangkok',
    '8': 'Asia/Taipei',
    // '545': 'Asia/Kathmandu',
    '9': 'Asia/Seoul',
    '930': 'Australia/Adelaide',
    '10': 'Australia/Brisbane',
    '11': 'Australia/Sydney',
    '12': 'Pacific/Auckland',
    '1245': 'Pacific/Chatham',
    '13': 'Pacific/Fakaofo',
    '1345': 'Pacific/Fakaofo',
};

export const tvtimezones =
    [
        'Pacific/Norfolk',       // Not supporting
        'Pacific/Honolulu',
        'America/Juneau',         // Not Upporting
        'America/Juneau',
        'America/Los_Angeles',
        'America/Phoenix',
        'America/El_Salvador',
        'America/Bogota',
        'America/Toronto',
        'America/Argentina/Buenos_Aires',
        'Europe/London',
        'Etc/UTC',
        'Europe/London',
        'Europe/Madrid',
        'Europe/Moscow',
        'Asia/Tehran',
        'Asia/Dubai',
        'Asia/Ashkhabad',
        'Asia/Kolkata',
        'Asia/Almaty',
        'Asia/Bangkok',
        'Asia/Taipei',
        'Asia/Kathmandu',
        'Asia/Seoul',
        'Australia/Adelaide',
        'Australia/Brisbane',
        'Australia/Sydney',
        'Pacific/Auckland',
        'Pacific/Chatham',
        'Pacific/Fakaofo',
        'Europe/Athens',
    ]